import { ReactNode } from "react"
import { Header } from "@widgets/header"
import { Footer } from "@widgets/footer"
import type { Metadata } from "next"

export const metadata: Metadata = {
    title: {
        template: "Pizza | %s",
        default: "Pizza",
    },
    description: "Generated by create next app",
}

interface ClientLayoutProps {
    children: ReactNode
}

export default function ClientLayout({ children }: ClientLayoutProps) {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    )
}
