import { ReactNode } from "react"
import type { Metadata } from "next"
import { Sidebar } from "@widgets/sidebar"
import { Button, InputControl, InputField, InputRoot, InputSlot } from "@shared/ui"
import { Bell, Mail, Search } from "lucide-react"

export const metadata: Metadata = {
    title: {
        template: "Dashboard | %s",
        default: "Dashboard",
    },
    description: "Generated by create next app",
}

interface DashboardLayoutProps {
    children: ReactNode
}

export default function DashboardLayout({ children }: DashboardLayoutProps) {
    return (
        <div className="flex min-h-screen w-full gap-4 bg-[#FAFAFA] p-4">
            <Sidebar />
            <div className="flex-1">
                <header className="flex items-center justify-between gap-10">
                    <div className="max-w-max">
                        <div className="text-3xl font-semibold">Hello Dorin</div>
                        <div>administrator</div>
                    </div>

                    <div className="flex flex-1 items-center justify-end gap-4">
                        <InputRoot className="max-w-112.5">
                            <InputControl variant="secondary" inputSize="lg">
                                <InputSlot>
                                    <Search />
                                </InputSlot>
                                <InputField name="search" placeholder="Search..." />
                            </InputControl>
                        </InputRoot>

                        <div className="flex items-center gap-2">
                            <Button onlyIcon kind="outline">
                                <Bell />
                            </Button>
                            <Button onlyIcon kind="outline">
                                <Mail />
                            </Button>
                        </div>
                    </div>
                </header>
                {children}
            </div>
        </div>
    )
}
