import { ReactNode } from "react"
import type { Metadata } from "next"
import { Sidebar } from "@widgets/dashboard/sidebar"
import { Header } from "@widgets/dashboard/header"

export const metadata: Metadata = {
    title: {
        template: "Dashboard | %s",
        default: "Dashboard",
    },
    description: "Generated by create next app",
}

interface DashboardLayoutProps {
    children: ReactNode
}

export default function DashboardLayout({ children }: DashboardLayoutProps) {
    return (
        <div className="flex min-h-screen w-full gap-4 bg-[#FAFAFA]">
            <Sidebar />
            <div className="flex-1 space-y-4 p-4">
                <Header />
                {children}
            </div>
        </div>
    )
}
